In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
df=pd.read_excel("/content/Delinquency_prediction_dataset.xlsx")

In [ ]:
df.head()

,Customer_ID,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,Account_Tenure,Credit_Card_Type,Location,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6
0,CUST0001,56,165580.0,398.0,0.390502,3,0,16310.0,0.317396,EMP,18,Student,Los Angeles,Late,Late,Missed,Late,Missed,Late
1,CUST0002,69,100999.0,493.0,0.312444,6,1,17401.0,0.196093,Self-employed,0,Standard,Phoenix,Missed,Missed,Late,Missed,On-time,On-time
2,CUST0003,46,188416.0,500.0,0.359930,0,0,13761.0,0.301655,Self-employed,1,Platinum,Chicago,Missed,Late,Late,On-time,Missed,Late
3,CUST0004,32,101672.0,413.0,0.371400,3,0,88778.0,0.264794,Unemployed,15,Platinum,Phoenix,Late,Missed,Late,Missed,Late,Late
4,CUST0005,60,38524.0,487.0,0.234716,2,0,13316.0,0.510583,Self-employed,11,Standard,Phoenix,Missed,On-time,Missed,Late,Late,Late


In [ ]:
df.columns

Index(['Customer_ID', 'Age', 'Income', 'Credit_Score', 'Credit_Utilization',
       'Missed_Payments', 'Delinquent_Account', 'Loan_Balance',
       'Debt_to_Income_Ratio', 'Employment_Status', 'Account_Tenure',
       'Credit_Card_Type', 'Location', 'Month_1', 'Month_2', 'Month_3',
       'Month_4', 'Month_5', 'Month_6'],
      dtype='object')

In [ ]:
df.dtypes

,0
Customer_ID,object
Age,int64
Income,float64
Credit_Score,float64
Credit_Utilization,float64
Missed_Payments,int64
Delinquent_Account,int64
Loan_Balance,float64
Debt_to_Income_Ratio,float64
Employment_Status,object


In [ ]:
df.isnull().sum()

,0
Customer_ID,0
Age,0
Income,0
Credit_Score,0
Credit_Utilization,0
Missed_Payments,0
Delinquent_Account,0
Loan_Balance,0
Debt_to_Income_Ratio,0
Employment_Status,0


In [ ]:
income_groupedBy_age = df.groupby('Age')['Income'].mean()

df['Income'] = df['Income'].fillna(df['Age'].map(income_groupedBy_age))

In [ ]:
credit_group_groupedBy_age = df.groupby('Age')['Credit_Score'].mean()

df['Credit_Score'] = df['Credit_Score'].fillna(df['Age'].map(credit_group_groupedBy_age))

In [ ]:
df['Loan_Balance']

,Loan_Balance
0,16310.0
1,17401.0
2,13761.0
3,88778.0
4,13316.0
...,...
496,45595.0
497,44449.0
498,11155.0
499,36968.0


In [ ]:
# Step 1: Fill using grouped mean
loan_groupedBy_age = df.groupby('Age')['Loan_Balance'].mean()

df['Loan_Balance'] = df['Loan_Balance'].fillna(
    df['Age'].map(loan_groupedBy_age)
)

# Step 2: Fill remaining nulls using overall mean
df['Loan_Balance'] = df['Loan_Balance'].fillna(
    df['Loan_Balance'].mean()
)

In [33]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.isnull().sum()

,0
Customer_ID,0
Age,0
Income,0
Credit_Score,0
Credit_Utilization,0
Missed_Payments,0
Delinquent_Account,0
Loan_Balance,0
Debt_to_Income_Ratio,0
Employment_Status,0


In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
le=LabelEncoder()

In [38]:
df.columns

Index(['Customer_ID', 'Age', 'Income', 'Credit_Score', 'Credit_Utilization',
       'Missed_Payments', 'Delinquent_Account', 'Loan_Balance',
       'Debt_to_Income_Ratio', 'Employment_Status', 'Account_Tenure',
       'Credit_Card_Type', 'Location', 'Month_1', 'Month_2', 'Month_3',
       'Month_4', 'Month_5', 'Month_6'],
      dtype='object')

In [66]:
df.head()

,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Account_Tenure,Employment_Status_Employed,...,Month_3_On-time,Month_4_Late,Month_4_Missed,Month_4_On-time,Month_5_Late,Month_5_Missed,Month_5_On-time,Month_6_Late,Month_6_Missed,Month_6_On-time
0,56,165580.0,398.0,0.390502,3,0,16310.0,0.317396,18,True,...,False,True,False,False,False,True,False,True,False,False
1,69,100999.0,493.0,0.312444,6,1,17401.0,0.196093,0,False,...,False,False,True,False,False,False,True,False,False,True
2,46,188416.0,500.0,0.359930,0,0,13761.0,0.301655,1,False,...,False,False,False,True,False,True,False,True,False,False
3,32,101672.0,413.0,0.371400,3,0,88778.0,0.264794,15,False,...,False,False,True,False,True,False,False,True,False,False
4,60,38524.0,487.0,0.234716,2,0,13316.0,0.510583,11,False,...,False,True,False,False,True,False,False,True,False,False


In [51]:
df['Employment_Status'] = df['Employment_Status'].replace({
    'EMP': 'Employed',
    'employed': 'Employed',
    'retired': 'Retired',
    '0': 'Unknown'
})

In [52]:
df['Employment_Status'].value_counts()

,count
Employment_Status,
Employed,240
Unemployed,93
Retired,87
Self-employed,80
0,1


In [53]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [55]:
df = pd.get_dummies(df, columns=['Employment_Status'], drop_first=True)

In [56]:
df.dtypes

,0
Customer_ID,object
Age,int64
Income,float64
Credit_Score,float64
Credit_Utilization,float64
Missed_Payments,int64
Delinquent_Account,int64
Loan_Balance,float64
Debt_to_Income_Ratio,float64
Account_Tenure,int64


In [83]:
from sklearn.model_selection import train_test_split

In [84]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [85]:
df.select_dtypes(include='object').columns

Index([], dtype='object')

In [65]:
df = pd.get_dummies(df, drop_first=True)

In [69]:
X = df.drop(['Delinquent_Account'], axis=1)
y = df['Delinquent_Account']

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [86]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(class_weight='balanced', max_iter=1000)


In [87]:
model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(class_weight='balanced', max_iter=1000)

In [88]:
y_pred=model.predict(X_test)
y_pred

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0])

In [91]:
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix, roc_auc_score


In [93]:
print("Accuracy = ",accuracy_score(y_test,y_pred))
print("\n")
print("Classification Report : \n" ,classification_report(y_test,y_pred))
print("\n")
print("Confusion Matrix : \n" ,confusion_matrix(y_test,y_pred))
print("\n")
print("ROC_AUC_SCORE : ",roc_auc_score(y_test,y_pred))
print("\n")

Accuracy =  0.4752475247524752


Classification Report : 
               precision    recall  f1-score   support

           0       0.84      0.48      0.61        87
           1       0.12      0.43      0.18        14

    accuracy                           0.48       101
   macro avg       0.48      0.46      0.40       101
weighted avg       0.74      0.48      0.55       101



Confusion Matrix : 
 [[42 45]
 [ 8  6]]


ROC_AUC_SCORE :  0.4556650246305418




RANDOM FOREST

In [94]:
from sklearn.ensemble import  RandomForestClassifier

In [95]:
rf_model=RandomForestClassifier(random_state=42)

In [96]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [97]:
y_pred=rf_model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [108]:
print("Evaluation Metrics Using Random Forest \n")
print("Accuracy = ",accuracy_score(y_test,y_pred))
print("\n")
print("Classification Report : \n" ,classification_report(y_test,y_pred))
print("\n")
print("Confusion Report : \n",confusion_matrix(y_test,y_pred))
print("\n")

Evaluation Metrics Using Random Forest 

Accuracy =  0.8316831683168316


Classification Report : 
               precision    recall  f1-score   support

           0       0.87      0.94      0.91        87
           1       0.29      0.14      0.19        14

    accuracy                           0.83       101
   macro avg       0.58      0.54      0.55       101
weighted avg       0.79      0.83      0.81       101



Confusion Report : 
 [[82  5]
 [12  2]]




Decision **Tree**

In [100]:
from sklearn.tree import DecisionTreeClassifier

In [101]:
dt_model=DecisionTreeClassifier(random_state=42)

In [104]:
dt_model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [105]:
y_pred=dt_model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [106]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print("Accuracy = ",accuracy_score(y_test,y_pred))
print("\n")
print("Classification Report : \n" ,classification_report(y_test,y_pred))
print("\n")
print("Confusion Report : \n",confusion_matrix(y_test,y_pred))
print("\n")

Accuracy =  0.8316831683168316


Classification Report : 
               precision    recall  f1-score   support

           0       0.87      0.94      0.91        87
           1       0.29      0.14      0.19        14

    accuracy                           0.83       101
   macro avg       0.58      0.54      0.55       101
weighted avg       0.79      0.83      0.81       101



Confusion Report : 
 [[82  5]
 [12  2]]




In [107]:
from google.colab import files

files.download('/content/Delinquency_prediction_dataset.xlsx')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>